[package]
name = "CubeExplorer"
version = "0.1.0"
authors = ["Vincent Wong <vincent@vwong.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18.0"
