[package]
name = "cubesim"
version = "0.1.0"
authors = ["Vincent Wong <vincent@vwong.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cgmath = "0.18.0"
derive_more = "0.99.16"

[dev-dependencies]
criterion = "0.3.5"
